LANGUAGES = {
    "RU": {
        "title": "Speed Chime — Powered by Gemini AI",
        "settings": "Настройки",
        "threshold": "Лимит скорости (км/ч):",
        "sound_file": "Свой звук (опционально):",
        "lang": "Язык / Language:",
        "browse": "Обзор...",
        "test": "Тест",
        "live": "Телеметрия",
        "log_title": "Журнал (Логи)",
        "start": "Старт",
        "stop": "Стоп",
        "quit": "Выход",
        "footer": "Разработано совместно с ИИ (Gemini)",
        "speed_no_data": "Скорость: НЕТ ДАННЫХ",
        "chime_on": "Звук: ВКЛ",
        "chime_off": "Звук: выкл",
        "test_first_stop": "Сначала нажмите 'Стоп' для теста звука.",
        "err_pygame": "Ошибка: Модуль 'pygame' не найден.",
        "testing_sound": "Тест звука (5 секунд)...",
        "started": "Отслеживание запущено! Лимит >= {} км/ч",
        "stopped": "Отслеживание остановлено.",
        "theme_light": "☀️ Светлая",
        "theme_dark": "🌙 Тёмная"
    },
    "EN": {
        "title": "Speed Chime — Powered by Gemini AI",
        "settings": "Settings",
        "threshold": "Speed threshold (km/h):",
        "sound_file": "Sound file (optional):",
        "lang": "Language:",
        "browse": "Browse...",
        "test": "Test",
        "live": "Live telemetry",
        "log_title": "Log",
        "start": "Start",
        "stop": "Stop",
        "quit": "Quit",
        "footer": "Developed with AI assistance (Gemini)",
        "speed_no_data": "Speed: NO DATA",
        "chime_on": "Chime: ON",
        "chime_off": "Chime: off",
        "test_first_stop": "Please click 'Stop' first to test the sound.",
        "err_pygame": "Error: Module 'pygame' not found.",
        "testing_sound": "Testing sound (5 seconds)...",
        "started": "Listener started! Armed >= {} km/h",
        "stopped": "Listener stopped.",
        "theme_light": "☀️ Light",
        "theme_dark": "🌙 Dark"
    }
}